- hosts: all
  become: true
  environment:
    DEBUG: true
  tasks:
  - name: copy app
    copy:
      src: "{{ inventory_dir }}/../app"
      dest: /
      directory_mode: yes
  - name: pip install
    shell: pip install -r requirements.txt
    args:
      chdir: /app
